#!/usr/bin/env python3
"""Generate the synthetic Bungie-shaped fixtures in Career Stats Shared/fixtures.

Everything this writes is invented. The shapes are Bungie's -- the platform envelope, the
values dictionaries, the manifest layout -- so that loading a fixture exercises the real
mapping code in Destiny.Client rather than a shortcut around it. The numbers are not
recorded from any player.

The generated career deliberately contains a true, findable trend: K/D climbs from roughly
0.90 to roughly 1.40 across the ninety days, and the win rate climbs with it. That is there
so the trend charts have something real to detect and so the significance test in Trends.cs
has a reason to say "improving" rather than "steady".

Run:  python Destiny Career Stats/tools/generate-fixtures.py
"""

from __future__ import annotations

import json
import math
import os
import random
from datetime import datetime, timedelta, timezone

SEED = 20260904
OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "shared", "fixtures"
)
OUT = os.path.normpath(OUT)

NOTE = (
    "SYNTHETIC FIXTURE. Generated by Destiny Career Stats/tools/"
    "generate-fixtures.py. Shaped like a real Bungie.net API response; the numbers are "
    "invented and belong to no player."
)

END = datetime(2026, 9, 3, 22, 0, 0, tzinfo=timezone.utc)
DAYS = 90
MATCH_TARGET = 120

MEMBERSHIP_TYPE = 3  # Steam
MEMBERSHIP_ID = "4611686018400119004"
CHARACTERS = ["2305843009300010001", "2305843009300010002", "2305843009300010003"]

MANIFEST_VERSION = "ana-fixture.2026.09.03.1200-1-bnet.00000"
ACTIVITY_TABLE_PATH = (
    "/common/destiny2_content/json/en/DestinyActivityDefinition-ana-fixture.json"
)
MODE_TABLE_PATH = (
    "/common/destiny2_content/json/en/DestinyActivityModeDefinition-ana-fixture.json"
)

# (modeType, category, label). Category 2 is PvP, 3 is PvE competitive (Gambit), 1 is PvE.
MODES = {
    10: ("Control", 2),
    12: ("Clash", 2),
    48: ("Rumble", 2),
    37: ("Survival", 2),
    43: ("Iron Banner Control", 2),
    84: ("Trials of Osiris", 2),
    63: ("Gambit", 3),
    3: ("Strike", 1),
    46: ("Nightfall", 1),
    82: ("Dungeon", 1),
    4: ("Raid", 1),
}

# hash -> (name, modeType, isPvP, icon)
ACTIVITIES = {
    3628169985: ("Rusted Lands", 10, True),
    2570313480: ("Bannerfall", 10, True),
    1071510797: ("Endless Vale", 12, True),
    1219083526: ("Javelin-4", 12, True),
    2337227635: ("Altar of Flame", 48, True),
    3696775682: ("Widow's Court", 48, True),
    2571459698: ("Midtown", 37, True),
    3821020454: ("Convergence", 37, True),
    1445655833: ("Burnout", 43, True),
    2624692004: ("Cathedral of Dusk", 43, True),
    1071087784: ("Eternity", 84, True),
    3011324617: ("Wormhaven", 84, True),
    2827858605: ("Gambit", 63, False),
    1102201127: ("The Inverted Spire", 3, False),
    3849697860: ("The Scarlet Keep", 3, False),
    2599001913: ("The Glassway", 46, False),
    3373582085: ("Warden of Nothing", 46, False),
    1077850348: ("Prophecy", 82, False),
    4078656106: ("Grasp of Avarice", 82, False),
    1441982566: ("King's Fall", 4, False),
    2192826039: ("Root of Nightmares", 4, False),
}

# Playlist definitions, so directorActivityHash differs from referenceId the way it does
# in real data.
PLAYLISTS = {
    2: ("Quickplay", 10),
    3: ("Competitive", 37),
    4: ("Iron Banner", 43),
    5: ("Trials of Osiris", 84),
    6: ("Vanguard Ops", 3),
    7: ("Nightfall: The Ordeal", 46),
    8: ("Gambit", 63),
}
PLAYLIST_HASHES = {
    10: 2166136261,
    12: 2166136262,
    48: 2166136263,
    37: 2166136264,
    43: 2166136265,
    84: 2166136266,
    3: 2166136267,
    46: 2166136268,
    63: 2166136269,
}

# How often each mode is played. Weighted towards Crucible so the competitive trend basis
# has enough matches to be worth plotting.
MODE_WEIGHTS = [
    (10, 22), (12, 14), (48, 10), (37, 14), (43, 8), (84, 6),
    (63, 10), (3, 8), (46, 5), (82, 2), (4, 1),
]


def value(stat_id: str, raw: float, display: str | None = None) -> dict:
    """One DestinyHistoricalStatsValue, in Bungie's shape."""
    if display is None:
        display = f"{raw:.0f}" if float(raw).is_integer() else f"{raw:.2f}"
    return {"statId": stat_id, "basic": {"value": raw, "displayValue": display}}


def envelope(response, note: str = NOTE) -> dict:
    return {
        "_note": note,
        "Response": response,
        "ErrorCode": 1,
        "ThrottleSeconds": 0,
        "ErrorStatus": "Success",
        "Message": "Ok",
        "MessageData": {},
    }


def write(name: str, payload) -> None:
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=1, ensure_ascii=False)
        handle.write("\n")
    print(f"wrote {path} ({os.path.getsize(path)} bytes)")


def skill(t: float) -> float:
    """K/D skill curve across the window. t runs 0 (oldest) to 1 (newest)."""
    # A slightly S-shaped climb rather than a straight line, so the fitted slope is real
    # but the smoothed line still has something to do.
    return 0.90 + 0.50 * (0.35 * t + 0.65 * (1 / (1 + math.exp(-6 * (t - 0.45)))))


def win_chance(t: float) -> float:
    return 0.42 + 0.16 * t


def build_matches(rng: random.Random) -> list[dict]:
    """Lay ~120 matches over ~90 days in believable sessions."""
    play_days = sorted(rng.sample(range(DAYS), 46))
    sessions: list[tuple[int, int]] = []
    remaining = MATCH_TARGET
    for index, day in enumerate(play_days):
        left = len(play_days) - index
        count = max(1, min(6, round(remaining / left + rng.uniform(-1.2, 1.4))))
        count = min(count, remaining - (left - 1)) if left > 1 else remaining
        count = max(1, count)
        sessions.append((day, count))
        remaining -= count
        if remaining <= 0:
            break

    matches: list[dict] = []
    instance = 12000000000
    mode_pool = [m for m, w in MODE_WEIGHTS for _ in range(w)]

    for day, count in sessions:
        t = day / (DAYS - 1)
        # A session tends to stay in one activity type, the way people actually play.
        session_mode = rng.choice(mode_pool)
        start = END - timedelta(days=DAYS - 1 - day) - timedelta(hours=rng.uniform(0, 6))

        for slot in range(count):
            mode = session_mode if rng.random() < 0.72 else rng.choice(mode_pool)
            category = MODES[mode][1]
            candidates = [h for h, a in ACTIVITIES.items() if a[1] == mode]
            reference = rng.choice(candidates)

            instance += rng.randint(3, 97)
            period = start + timedelta(minutes=slot * rng.uniform(11, 26))

            # A session's own form wanders around the long-run trend.
            form = rng.gauss(0, 0.22)
            base = max(0.25, skill(t) + form)

            if category in (2, 3):
                duration = int(rng.uniform(430, 760)) if mode != 84 else int(rng.uniform(240, 520))
                deaths = max(0, int(round(rng.gauss(9.5, 3.0))))
                if mode == 84:
                    deaths = max(0, int(round(rng.gauss(2.4, 1.4))))
                kills = max(0, int(round(deaths * base + rng.gauss(0.6, 1.6))))
                if deaths == 0:
                    kills = max(kills, int(round(rng.uniform(4, 14))))
                assists = max(0, int(round(kills * rng.uniform(0.25, 0.65))))
                won = rng.random() < win_chance(t) + (0.10 if base > skill(t) else -0.06)
                standing = 0 if won else 1
                score = int(round(kills * rng.uniform(90, 135) + assists * 25))
                team_score = rng.choice([100, 90, 75]) if won else rng.randint(45, 89)
                players = 12 if mode in (10, 12, 43) else (6 if mode in (37, 48) else 6)
                if mode == 84:
                    players = 6
                if mode == 63:
                    players = 8
            else:
                duration = int(rng.uniform(900, 2600))
                deaths = max(0, int(round(rng.gauss(2.2, 1.9))))
                kills = int(round(rng.uniform(55, 190) * (0.8 + 0.4 * base)))
                assists = int(round(kills * rng.uniform(0.05, 0.2)))
                standing = None
                score = 0
                team_score = 0
                players = 3 if mode in (3, 46) else 6

            opponents = kills + assists
            efficiency = (kills + assists) / deaths if deaths else float(kills + assists)
            kd = kills / deaths if deaths else float(kills)
            kda = (kills + assists / 2) / deaths if deaths else float(kills + assists / 2)

            values = {
                "assists": value("assists", assists),
                "completed": value("completed", 1, "Yes"),
                "deaths": value("deaths", deaths),
                "kills": value("kills", kills),
                "opponentsDefeated": value("opponentsDefeated", opponents),
                "efficiency": value("efficiency", round(efficiency, 4), f"{efficiency:.2f}"),
                "killsDeathsRatio": value("killsDeathsRatio", round(kd, 4), f"{kd:.2f}"),
                "killsDeathsAssists": value("killsDeathsAssists", round(kda, 4), f"{kda:.2f}"),
                "activityDurationSeconds": value(
                    "activityDurationSeconds", duration, f"{duration // 60}m {duration % 60}s"
                ),
                "completionReason": value("completionReason", 0, "Objective Completed"),
                "fireteamId": value("fireteamId", 0),
                "startSeconds": value("startSeconds", 0),
                "timePlayedSeconds": value(
                    "timePlayedSeconds", duration, f"{duration // 60}m {duration % 60}s"
                ),
                "playerCount": value("playerCount", players),
                "teamScore": value("teamScore", team_score),
                "score": value("score", score),
            }
            if standing is not None:
                values["standing"] = value(
                    "standing", standing, "Victory" if standing == 0 else "Defeat"
                )

            matches.append(
                {
                    "character": rng.choice(CHARACTERS),
                    "period": period.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "activityDetails": {
                        "referenceId": reference,
                        "directorActivityHash": PLAYLIST_HASHES.get(mode, reference),
                        "instanceId": str(instance),
                        "mode": mode,
                        "modes": sorted({5 if category == 2 else 7, mode}),
                        "isPrivate": False,
                        "membershipType": MEMBERSHIP_TYPE,
                    },
                    "values": values,
                }
            )

    matches.sort(key=lambda m: m["period"], reverse=True)
    return matches


def all_time(entered, won, kills, deaths, assists, seconds, precision):
    """An allTime block, with the stat ids Bungie actually publishes in the General group."""
    kd = kills / deaths if deaths else float(kills)
    kda = (kills + assists / 2) / deaths if deaths else float(kills)
    eff = (kills + assists) / deaths if deaths else float(kills)
    lost = max(0, entered - won)
    block = {
        "activitiesEntered": value("activitiesEntered", entered),
        "activitiesWon": value("activitiesWon", won),
        "assists": value("assists", assists),
        "kills": value("kills", kills),
        "deaths": value("deaths", deaths),
        "killsDeathsRatio": value("killsDeathsRatio", round(kd, 4), f"{kd:.2f}"),
        "killsDeathsAssists": value("killsDeathsAssists", round(kda, 4), f"{kda:.2f}"),
        "efficiency": value("efficiency", round(eff, 4), f"{eff:.2f}"),
        "precisionKills": value("precisionKills", precision),
        "secondsPlayed": value(
            "secondsPlayed", seconds, f"{seconds // 3600}h {(seconds % 3600) // 60}m"
        ),
        "averageLifespan": value("averageLifespan", 87.4, "1m 27s"),
        "longestKillSpree": value("longestKillSpree", 11),
        "bestSingleGameKills": value("bestSingleGameKills", 34),
        "suicides": value("suicides", 61),
        "score": value("score", entered * 1180),
    }
    if won:
        ratio = won / lost if lost else float(won)
        block["winLossRatio"] = value("winLossRatio", round(ratio, 4), f"{ratio:.2f}")
    return block


def main() -> None:
    rng = random.Random(SEED)
    os.makedirs(OUT, exist_ok=True)
    matches = build_matches(rng)
    print(f"{len(matches)} matches across {len({m['period'][:10] for m in matches})} days")

    # ---- player search -------------------------------------------------------------
    # The second card is deliberately a homoglyph name: it renders as "Elissu" but its
    # first character is U+0406, so a search for the typed version finds nothing. It is
    # here so Identity.LooksLikeHomoglyph has something real to catch.
    write(
        "destiny-search-player.json",
        envelope(
            [
                {
                    "iconPath": "/img/theme/destiny/icons/icon_steam.png",
                    "crossSaveOverride": 3,
                    "applicableMembershipTypes": [3, 1],
                    "isPublic": True,
                    "membershipType": 3,
                    "membershipId": MEMBERSHIP_ID,
                    "displayName": "AnaGuardian",
                    "bungieGlobalDisplayName": "AnaGuardian",
                    "bungieGlobalDisplayNameCode": 4412,
                },
                {
                    "iconPath": "/img/theme/destiny/icons/icon_xbl.png",
                    "crossSaveOverride": 0,
                    "applicableMembershipTypes": [1],
                    "isPublic": True,
                    "membershipType": 1,
                    "membershipId": "4611686018400220117",
                    "displayName": "Іlissu",
                    "bungieGlobalDisplayName": "Іlissu",
                    "bungieGlobalDisplayNameCode": 9007,
                },
            ],
            NOTE
            + " The second card's display name begins with U+0406, a Cyrillic letter that "
            "renders like a Latin I; it exists to exercise Identity.LooksLikeHomoglyph.",
        ),
    )

    # ---- memberships by id ---------------------------------------------------------
    write(
        "destiny-memberships.json",
        envelope(
            {
                "destinyMemberships": [
                    {
                        "iconPath": "/img/theme/destiny/icons/icon_steam.png",
                        "crossSaveOverride": 3,
                        "applicableMembershipTypes": [3, 1],
                        "isPublic": True,
                        "membershipType": 3,
                        "membershipId": MEMBERSHIP_ID,
                        "displayName": "AnaGuardian",
                        "bungieGlobalDisplayName": "AnaGuardian",
                        "bungieGlobalDisplayNameCode": 4412,
                    }
                ],
                "primaryMembershipId": MEMBERSHIP_ID,
                "bungieNetUser": {
                    "membershipId": "19901101",
                    "displayName": "AnaGuardian",
                    "uniqueName": "AnaGuardian#4412",
                },
            }
        ),
    )

    # ---- profile -------------------------------------------------------------------
    minutes = {c: 0 for c in CHARACTERS}
    for match in matches:
        minutes[match["character"]] += (
            match["values"]["activityDurationSeconds"]["basic"]["value"] // 60
        )

    classes = [(0, "Titan", "/common/destiny2_content/icons/ana-emblem-titan.jpg"),
               (1, "Hunter", "/common/destiny2_content/icons/ana-emblem-hunter.jpg"),
               (2, "Warlock", "/common/destiny2_content/icons/ana-emblem-warlock.jpg")]

    characters = {}
    for index, character in enumerate(CHARACTERS):
        class_type, _, emblem = classes[index]
        last = max(
            (m["period"] for m in matches if m["character"] == character),
            default=END.strftime("%Y-%m-%dT%H:%M:%SZ"),
        )
        characters[character] = {
            "membershipId": MEMBERSHIP_ID,
            "membershipType": MEMBERSHIP_TYPE,
            "characterId": character,
            "dateLastPlayed": last,
            "minutesPlayedThisSession": "0",
            # Lifetime, so much larger than the fetched window.
            "minutesPlayedTotal": str(int(minutes[character]) + 41000 + index * 5500),
            "light": 2010 - index * 5,
            "stats": {"1935470627": 2010 - index * 5},
            "raceHash": 3887404748,
            "genderHash": 2204441813,
            "classHash": [3655393761, 671679327, 2271682572][index],
            "raceType": index % 3,
            "classType": class_type,
            "genderType": index % 2,
            "emblemPath": emblem,
            "emblemBackgroundPath": emblem.replace(".jpg", "-bg.jpg"),
            "emblemHash": 1940590506 + index,
            "baseCharacterLevel": 50,
            "percentToNextLevel": 0.0,
        }

    write(
        "destiny-profile.json",
        envelope(
            {
                "responseMintedTimestamp": END.strftime("%Y-%m-%dT%H:%M:%SZ"),
                "profile": {
                    "data": {
                        "userInfo": {
                            "crossSaveOverride": 3,
                            "applicableMembershipTypes": [3, 1],
                            "isPublic": True,
                            "membershipType": MEMBERSHIP_TYPE,
                            "membershipId": MEMBERSHIP_ID,
                            "displayName": "AnaGuardian",
                            "bungieGlobalDisplayName": "AnaGuardian",
                            "bungieGlobalDisplayNameCode": 4412,
                            "iconPath": "/img/theme/destiny/icons/icon_steam.png",
                        },
                        "dateLastPlayed": matches[0]["period"],
                        "versionsOwned": 4127,
                        "characterIds": CHARACTERS,
                        "currentGuardianRank": 9,
                        "lifetimeHighestGuardianRank": 10,
                    },
                    "privacy": 1,
                },
                "characters": {"data": characters, "privacy": 1},
                # Requested by the client, deliberately unmapped: rendering either one needs
                # definition tables this tracker does not download.
                "profileRecords": {"data": {"score": 148900, "records": {}}, "privacy": 1},
                "metrics": {"data": {"metrics": {}}, "privacy": 1},
            }
        ),
    )

    # ---- historical stats ----------------------------------------------------------
    # Lifetime figures, much larger than the ninety-day window, the way a real account is.
    write(
        "destiny-historical-stats.json",
        envelope(
            {
                "allPvP": {
                    "allTime": all_time(
                        entered=3218,
                        won=1544,
                        kills=41980,
                        deaths=37115,
                        assists=13402,
                        seconds=2154600,
                        precision=13930,
                    )
                },
                "allPvE": {
                    "allTime": all_time(
                        entered=1907,
                        won=0,
                        kills=214880,
                        deaths=4188,
                        assists=9903,
                        seconds=3402900,
                        precision=71110,
                    )
                },
            }
        ),
    )

    # ---- activity history, one file per character ----------------------------------
    for character in CHARACTERS:
        rows = [
            {
                "period": m["period"],
                "activityDetails": m["activityDetails"],
                "values": m["values"],
            }
            for m in matches
            if m["character"] == character
        ]
        write(
            f"destiny-activities-{character}.json",
            envelope({"activities": rows}),
        )
        print(f"  character {character}: {len(rows)} activities")

    # ---- one post game carnage report ----------------------------------------------
    newest = matches[0]
    write(
        f"destiny-pgcr-{newest['activityDetails']['instanceId']}.json",
        envelope(
            {
                "period": newest["period"],
                "startingPhaseIndex": 0,
                "activityWasStartedFromBeginning": True,
                "activityDetails": newest["activityDetails"],
                "entries": [
                    {
                        "standing": int(
                            newest["values"].get("standing", {})
                            .get("basic", {})
                            .get("value", 0)
                        ),
                        "score": value("score", newest["values"]["score"]["basic"]["value"]),
                        "player": {
                            "destinyUserInfo": {
                                "iconPath": "/img/theme/destiny/icons/icon_steam.png",
                                "crossSaveOverride": 3,
                                "isPublic": True,
                                "membershipType": MEMBERSHIP_TYPE,
                                "membershipId": MEMBERSHIP_ID,
                                "displayName": "AnaGuardian",
                                "bungieGlobalDisplayName": "AnaGuardian",
                                "bungieGlobalDisplayNameCode": 4412,
                            },
                            "characterClass": "Hunter",
                            "classHash": 671679327,
                            "characterLevel": 50,
                            "lightLevel": 2010,
                            "emblemHash": 1940590506,
                        },
                        "characterId": newest["character"],
                        "values": newest["values"],
                        "extended": {
                            # precisionKills is the only accuracy-shaped number Bungie
                            # publishes anywhere, and it only appears here.
                            "values": {
                                "precisionKills": value(
                                    "precisionKills",
                                    max(
                                        1,
                                        int(
                                            newest["values"]["kills"]["basic"]["value"] * 0.34
                                        ),
                                    ),
                                ),
                                "weaponKillsGrenade": value("weaponKillsGrenade", 3),
                                "weaponKillsMelee": value("weaponKillsMelee", 2),
                                "weaponKillsSuper": value("weaponKillsSuper", 4),
                                "weaponKillsAbility": value("weaponKillsAbility", 1),
                            },
                            "weapons": [
                                {
                                    "referenceId": 3535742959,
                                    "values": {
                                        "uniqueWeaponKills": value("uniqueWeaponKills", 9),
                                        "uniqueWeaponPrecisionKills": value(
                                            "uniqueWeaponPrecisionKills", 5
                                        ),
                                        "uniqueWeaponKillsPrecisionKills": value(
                                            "uniqueWeaponKillsPrecisionKills",
                                            0.5556,
                                            "56%",
                                        ),
                                    },
                                }
                            ],
                        },
                    }
                ],
                "teams": [
                    {
                        "teamId": 17,
                        "standing": value("standing", 0, "Victory"),
                        "score": value("score", 100),
                        "teamName": "Alpha",
                    },
                    {
                        "teamId": 18,
                        "standing": value("standing", 1, "Defeat"),
                        "score": value("score", 87),
                        "teamName": "Bravo",
                    },
                ],
            }
        ),
    )

    # ---- manifest ------------------------------------------------------------------
    write(
        "destiny-manifest.json",
        envelope(
            {
                "version": MANIFEST_VERSION,
                "mobileAssetContentPath": "/common/destiny2_content/sqlite/asset/ana-fixture.content",
                "mobileWorldContentPaths": {"en": "/common/destiny2_content/sqlite/en/ana-fixture.content"},
                "jsonWorldContentPaths": {
                    "en": "/common/destiny2_content/json/en/aggregate-ana-fixture.json"
                },
                # The tracker reads only these two tables, which is the whole reason it
                # never downloads the world content file above.
                "jsonWorldComponentContentPaths": {
                    "en": {
                        "DestinyActivityDefinition": ACTIVITY_TABLE_PATH,
                        "DestinyActivityModeDefinition": MODE_TABLE_PATH,
                        "DestinyInventoryItemDefinition": "/common/destiny2_content/json/en/DestinyInventoryItemDefinition-ana-fixture.json",
                    }
                },
            }
        ),
    )

    # ---- definition tables (no envelope: these are plain CDN files) ------------------
    activity_table = {"_note": NOTE}
    for hash_value, (name, mode, is_pvp) in ACTIVITIES.items():
        activity_table[str(hash_value)] = {
            "displayProperties": {
                "description": f"{name}.",
                "name": name,
                "icon": "/common/destiny2_content/icons/ana-fixture-activity.png",
                "hasIcon": True,
            },
            "originalDisplayProperties": {"name": name, "hasIcon": False},
            "pgcrImage": "/img/theme/destiny/bgs/pgcrs/ana-fixture.jpg",
            "activityLightLevel": 1350,
            "destinationHash": 2777041980,
            "placeHash": 2961497387,
            "activityTypeHash": 2043403989,
            "tier": -1,
            "isPlaylist": False,
            "directActivityModeType": mode,
            "activityModeTypes": sorted({5 if is_pvp else 7, mode}),
            "isPvP": is_pvp,
            "hash": hash_value,
            "index": len(activity_table),
            "redacted": False,
        }
    for mode, playlist_hash in PLAYLIST_HASHES.items():
        label = next((p[0] for p in PLAYLISTS.values() if p[1] == mode), MODES[mode][0])
        activity_table[str(playlist_hash)] = {
            "displayProperties": {
                "description": f"{label} playlist.",
                "name": label,
                "icon": "/common/destiny2_content/icons/ana-fixture-playlist.png",
                "hasIcon": True,
            },
            "isPlaylist": True,
            "directActivityModeType": mode,
            "activityModeTypes": [mode],
            "isPvP": MODES[mode][1] == 2,
            "hash": playlist_hash,
            "index": len(activity_table),
            "redacted": False,
        }
    write("destiny-activity-definitions.json", activity_table)

    mode_table = {"_note": NOTE}
    aggregates = {5: ("All PvP", 2), 7: ("All PvE", 1)}
    for mode, (label, category) in {**MODES, **aggregates}.items():
        mode_hash = 1000000000 + mode
        mode_table[str(mode_hash)] = {
            "displayProperties": {
                "description": f"{label}.",
                "name": label,
                "icon": "/common/destiny2_content/icons/ana-fixture-mode.png",
                "hasIcon": True,
            },
            "pgcrImage": "/img/theme/destiny/bgs/pgcrs/ana-fixture-mode.jpg",
            "modeType": mode,
            "activityModeCategory": category,
            "isTeamBased": mode not in (48, 3, 46, 82),
            "isAggregateMode": mode in (5, 7),
            "parentHashes": [],
            "friendlyName": label.lower().replace(" ", "_"),
            "hash": mode_hash,
            "index": len(mode_table),
            "redacted": False,
        }
    write("destiny-activity-mode-definitions.json", mode_table)

    # ---- an error fixture ----------------------------------------------------------
    # HTTP 200 with a failing ErrorCode is the single most common Bungie API trap. Having
    # it on disk means the test for it reads exactly like the real thing.
    write(
        "destiny-error-privacy.json",
        {
            "_note": NOTE
            + " This one is a FAILURE response, served with HTTP 200. ErrorCode 1665 is "
            "DestinyPrivacyRestriction. Checking the status code instead of ErrorCode "
            "would read this as a successful empty career.",
            "ErrorCode": 1665,
            "ThrottleSeconds": 0,
            "ErrorStatus": "DestinyPrivacyRestriction",
            "Message": "Your privacy settings, or the privacy settings of the account you are "
            "trying to view, do not allow this data to be shown.",
            "MessageData": {},
        },
    )

    write(
        "destiny-error-throttled.json",
        {
            "_note": NOTE
            + " A throttle response, also HTTP 200. ErrorCode 51 is "
            "PerEndpointRequestThrottleExceeded and ThrottleSeconds says how long to wait.",
            "ErrorCode": 51,
            "ThrottleSeconds": 4,
            "ErrorStatus": "PerEndpointRequestThrottleExceeded",
            "Message": "Too many requests. Please wait and try again.",
            "MessageData": {},
        },
    )

    # ---- a summary, so a human can sanity check the trend ---------------------------
    competitive = [m for m in matches if "standing" in m["values"]]
    half = len(competitive) // 2
    newer = competitive[:half]
    older = competitive[half:]

    def kd(rows):
        kills = sum(r["values"]["kills"]["basic"]["value"] for r in rows)
        deaths = sum(r["values"]["deaths"]["basic"]["value"] for r in rows)
        return kills / deaths if deaths else float(kills)

    def wr(rows):
        wins = sum(
            1 for r in rows if r["values"]["standing"]["basic"]["value"] == 0
        )
        return wins / len(rows) if rows else 0.0

    print()
    print(f"total matches      : {len(matches)}")
    print(f"competitive matches: {len(competitive)}")
    print(f"K/D  older half    : {kd(older):.2f}")
    print(f"K/D  newer half    : {kd(newer):.2f}")
    print(f"win% older half    : {wr(older) * 100:.1f}")
    print(f"win% newer half    : {wr(newer) * 100:.1f}")


if __name__ == "__main__":
    main()
