"""
Generate the raw API-shaped Xbox fixtures for Career Stats Shared/fixtures/xbox.

These mimic what achievements.xboxlive.com, titlehub.xboxlive.com and
profile.xboxlive.com actually return, so that loading them exercises the real
mapping code in AchievementMapper rather than a shortcut.

Deterministic: seeded RNG, fixed reference date. Re-running produces byte-identical
output, so a fixture diff always means someone changed the generator on purpose.
"""

import json
import random
from datetime import datetime, timedelta, timezone

SEED = 20260904
random.seed(SEED)

# Fixed so the fixtures never drift with the wall clock. 90 days of history ending
# a few days before "today" as of authoring, which leaves recent-but-not-suspiciously
# fresh data in the recent feed.
END = datetime(2026, 8, 30, 21, 14, 0, tzinfo=timezone.utc)
START = END - timedelta(days=90)

HALO_TITLE_ID = 2043073184
HALO_SCID = "3f8f4d1a-9c25-4b0d-9a67-1f1b2f2a51e7"
XUID = "2814648798129555"
# U+0406 CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I, then Latin "lissu".
GAMERTAG = "Іlissu"

NOTE = (
    "SYNTHETIC FIXTURE - not real Xbox Live data. Hand-generated to mimic the shape of "
    "achievements.xboxlive.com (x-xbl-contract-version: 2) so that loading it exercises "
    "the real mapping code. No part of this file came from a live account, and the token "
    "and XUID values in it are invented. Generated by "
    "Career Stats Shared/fixtures/xbox/generate.py with seed %d." % SEED
)


def iso(dt):
    """Xbox's timestamp format: 7 fractional digits and a Z."""
    return dt.strftime("%Y-%m-%dT%H:%M:%S.") + "%07dZ" % (dt.microsecond * 10)


NEVER = "0001-01-01T00:00:00.0000000"

# ---------------------------------------------------------------------------------------
# Achievement catalogue. Names/descriptions are invented in a Halo idiom; none are copied
# from the real game's achievement list.
# ---------------------------------------------------------------------------------------

VERBS = [
    ("Zone Control", "Capture %d zones in matchmaking", "Capture zones to lock down the map."),
    ("Oddball Custodian", "Hold the skull for %d minutes total", "Keep the skull off the ground."),
    ("Flag Runner", "Score %d flag captures", "Run the flag home."),
    ("Grapple Artist", "Get %d kills within a second of a grapple", "Grapple, then punish."),
    ("Marksman", "Land %d headshots with a precision weapon", "Aim higher."),
    ("Overshield Denial", "Deny %d overshield pickups", "Take it before they do."),
    ("Warthog Wrangler", "Get %d splatter kills", "Drive it like you found it."),
    ("Repulsor Reflex", "Deflect %d incoming projectiles", "Send it back."),
    ("Sniper's Nest", "Land %d no-scope kills", "Trust the reticle."),
    ("Banished Bane", "Defeat %d Brute chieftains", "They fall eventually."),
    ("Silent Approach", "Complete a mission without raising an alarm", "Be quiet."),
    ("Ordnance Discipline", "Win %d rounds without dying", "Stay alive."),
    ("Squad Anchor", "Earn %d assists in one match", "Help the team."),
    ("Power Weapon Broker", "Secure %d power weapon spawns", "Timing is everything."),
    ("Cartographer", "Play a match on every launch map", "See the whole rotation."),
    ("Long Haul", "Play %d matches", "Keep playing."),
    ("Comeback Kid", "Win %d matches after trailing by ten", "Never surrender."),
    ("Perfect Kill", "Get %d perfect kills", "No wasted shots."),
    ("Vehicle Denial", "Destroy %d enemy vehicles", "Deny the map."),
    ("Objective First", "Score %d objective points", "The objective is the objective."),
]

SUFFIXES = ["Bronze", "Silver", "Gold", "Onyx", "Eternal", "Ascendant"]

# Gamerscore values Xbox actually uses.
SCORES = [5, 10, 10, 15, 20, 20, 25, 30, 50]


def build_catalogue(count):
    """A believable spread of achievements: cheap common ones, a few expensive rare ones."""
    catalogue = []
    for i in range(count):
        base, description, locked = VERBS[i % len(VERBS)]
        tier = SUFFIXES[(i // len(VERBS)) % len(SUFFIXES)]
        target = random.choice([10, 25, 50, 100, 150, 250, 500])
        score = SCORES[i % len(SCORES)]
        catalogue.append(
            {
                "index": i,
                "name": "%s: %s" % (base, tier),
                "description": description % target if "%d" in description else description,
                "locked": locked,
                "gamerscore": score,
                "target": target,
                "secret": i % 17 == 0,
            }
        )
    return catalogue


def unlock_schedule(n_unlocked):
    """
    Unlock timestamps across the 90 days, with a deliberately decaying rate.

    A real player unlocks a burst of achievements when they pick a game up and then tails
    off, so the daily rate here is an explicit exponential decay rather than a random
    draw. That matters for this project specifically: Trends.FitLine will only call a
    direction when the slope clears two standard errors, so a fixture whose trend came out
    of an unshaped RNG would frequently render as "steady" and prove nothing. This one has
    a real, reproducible decline in it for the charts to find.

    The decay constant is 32 days, giving roughly a 6:1 ratio between the first and last
    fortnight -- steep enough to be unmistakable, shallow enough to look like a person
    rather than a step function.
    """
    import math

    days = 90
    decay = 38.0
    floor = 0.22

    # An exponential decay plus a floor. The decay is the "picked it up, played it hard,
    # tailed off" shape; the floor is the fact that a player who still owns the game keeps
    # unlocking the occasional thing, so the last fortnight is thin rather than empty.
    weights = [math.exp(-d / decay) + floor for d in range(days)]

    # Weighted sampling rather than a deterministic allocation: allocation rounds every
    # late day down to zero and produces a month-long dead patch at the end, which no real
    # account looks like.
    chosen = random.choices(range(days), weights=weights, k=n_unlocked)
    counts = [0] * days
    for day in chosen:
        counts[day] += 1

    stamps = []
    for day, count in enumerate(counts):
        for _ in range(count):
            # Evening sessions, with variance, clamped inside the day.
            hour = min(23.4, max(9.0, random.gauss(20.5, 2.4)))
            stamps.append(
                START
                + timedelta(days=day)
                + timedelta(
                    hours=hour,
                    minutes=random.randrange(60),
                    seconds=random.randrange(60),
                    microseconds=random.randrange(1000000),
                )
            )

    stamps.sort()
    return [s for s in stamps if START <= s <= END]


def media_assets(index):
    return [
        {
            "name": "%08x-1c4e-4d6f-9b21-%012x" % (index * 2654435761 % (1 << 32), index * 40503 % (1 << 48)),
            "type": "Icon",
            "url": "https://images-eds-ssl.xboxlive.com/image?url=SYNTHETIC.fixture.icon.%d&format=png" % index,
        }
    ]


def rarity(index, unlocked_fraction):
    """
    Rarity, and deliberately absent on a few entries.

    Older titles omit the block entirely, and a mapper that assumes it is present throws
    on them. Leaving a handful out here means the fixture tests that path for free.
    """
    if index % 23 == 0:
        return None
    percentage = round(max(0.4, min(96.0, unlocked_fraction * 100 + random.gauss(0, 12))), 2)
    return {
        "currentCategory": "Rare" if percentage < 10 else "Common",
        "currentPercentage": percentage,
    }


def achievement_entry(item, title_id, title_name, scid, unlocked_at, progress_current):
    unlocked = unlocked_at is not None
    entry = {
        "id": str(item["index"] + 1),
        "serviceConfigId": scid,
        "name": item["name"],
        "titleAssociations": [{"name": title_name, "id": title_id}],
        "progressState": "Achieved" if unlocked else ("InProgress" if progress_current else "NotStarted"),
        "progression": {
            "requirements": [
                {
                    "id": "%08x-4e91-4a1f-8f5c-1b2c3d4e5f60" % ((item["index"] + 7) * 2246822519 % (1 << 32)),
                    # Strings on the wire, not numbers. This is the detail that makes
                    # invariant parsing matter: a culture-sensitive parse of "10" is fine,
                    # but of a decimal target is not.
                    "current": str(item["target"] if unlocked else progress_current),
                    "target": str(item["target"]),
                    "operationType": "SumInteger",
                    "valueType": "Integer",
                    "ruleParticipationType": "Individual",
                }
            ],
            # Locked achievements carry the year-1 sentinel, exactly as the live service does.
            "timeUnlocked": iso(unlocked_at) if unlocked else NEVER,
        },
        "mediaAssets": media_assets(item["index"]),
        "platforms": ["Durango", "WindowsOneCore"],
        "isSecret": item["secret"],
        "description": item["description"],
        "lockedDescription": "" if item["secret"] else item["locked"],
        "productId": "9nblggh4qghw",
        "achievementType": "Persistent",
        "participationType": "Individual",
        "timeWindow": None,
        "rewards": [
            {
                "name": None,
                "description": None,
                "value": str(item["gamerscore"]),
                "type": "Gamerscore",
                "mediaAsset": None,
                "valueType": "Int",
            }
        ],
        "estimatedTime": "00:15:00",
        "deeplink": "",
        "isRevoked": False,
    }

    r = rarity(item["index"], 0.35)
    if r is not None:
        entry["rarity"] = r

    return entry


def build_halo_achievements():
    """~120 achievements for Halo Infinite, ~2/3 unlocked across the 90-day window."""
    catalogue = build_catalogue(119)
    n_unlocked = 78
    stamps = unlock_schedule(n_unlocked)

    # Which achievements are unlocked: spread across the catalogue rather than a prefix,
    # so a mapper that assumed ordering would fail.
    unlocked_indices = sorted(random.sample(range(len(catalogue)), len(stamps)))
    unlock_by_index = dict(zip(unlocked_indices, stamps))

    entries = []
    for item in catalogue:
        at = unlock_by_index.get(item["index"])
        if at is None:
            # Partial progress on about half the locked ones.
            current = random.randrange(0, item["target"]) if random.random() < 0.5 else 0
        else:
            current = item["target"]
        entries.append(
            achievement_entry(item, HALO_TITLE_ID, "Halo Infinite", HALO_SCID, at, current)
        )

    return {
        "_note": NOTE,
        "achievements": entries,
        "pagingInfo": {"continuationToken": None, "totalRecords": len(entries)},
    }, unlock_by_index, catalogue


def build_recent(halo_doc, unlock_by_index, catalogue):
    """
    The cross-title recent feed: the last 40 unlocks, newest first, mixed across titles.

    The live endpoint returns achievements from every title the player has touched, so
    this one carries a second title as well -- otherwise the mapper's per-achievement
    title association would never be exercised with more than one value.
    """
    unlocked = [
        e
        for e in halo_doc["achievements"]
        if e["progressState"] == "Achieved"
    ]
    unlocked.sort(key=lambda e: e["progression"]["timeUnlocked"], reverse=True)
    recent = [json.loads(json.dumps(e)) for e in unlocked[:34]]

    # A handful from a second title, interleaved by timestamp.
    other_scid = "b52c9a3d-6f10-4e2b-8c77-9d4e0a1b2c3d"
    other = []
    for i in range(6):
        item = {
            "index": 900 + i,
            "name": "Sundered Vault: Stage %d" % (i + 1),
            "description": "Clear the vault encounter on heroic.",
            "locked": "Clear the vault encounter.",
            "gamerscore": [15, 20, 30][i % 3],
            "target": 3,
            "secret": False,
        }
        at = END - timedelta(days=random.uniform(1, 30), hours=random.uniform(0, 12))
        other.append(
            achievement_entry(item, 1824155023, "Sundered Vault", other_scid, at, 3)
        )

    combined = recent + other
    combined.sort(key=lambda e: e["progression"]["timeUnlocked"], reverse=True)

    return {
        "_note": NOTE,
        "achievements": combined,
        "pagingInfo": {"continuationToken": None, "totalRecords": len(combined)},
    }


def build_titlehub(halo_doc):
    achievements = halo_doc["achievements"]
    earned = [e for e in achievements if e["progressState"] == "Achieved"]

    def score(entries):
        return sum(
            int(r["value"])
            for e in entries
            for r in e["rewards"]
            if r["type"] == "Gamerscore"
        )

    total_gs = score(achievements)
    earned_gs = score(earned)
    last_unlock = max(e["progression"]["timeUnlocked"] for e in earned)

    return {
        "_note": NOTE,
        "xuid": XUID,
        "titles": [
            {
                "titleId": str(HALO_TITLE_ID),
                "pfn": "Microsoft.HaloInfinite_8wekyb3d8bbwe",
                "bingId": "9c1e0000-0000-1000-8000-000000000001",
                "serviceConfigId": HALO_SCID,
                "windowsPhoneProductId": None,
                "name": "Halo Infinite",
                "type": "Game",
                "devices": ["PC", "XboxOne", "XboxSeries"],
                "displayImage": "https://store-images.s-microsoft.com/image/SYNTHETIC.fixture.boxart.halo",
                "mediaItemType": "Application",
                "modernTitleId": str(HALO_TITLE_ID),
                "isBundle": False,
                "achievement": {
                    "currentAchievements": len(earned),
                    "totalAchievements": len(achievements),
                    "currentGamerscore": earned_gs,
                    "totalGamerscore": total_gs,
                    "progressPercentage": round(earned_gs / total_gs * 100, 1),
                    "sourceVersion": 1,
                },
                "stats": {"sourceVersion": 0},
                "gamePass": {"isGamePass": True},
                "images": None,
                # The field the mapper reads for LastPlayed. Deliberately later than the
                # last unlock: you keep playing after you stop unlocking things, and a
                # mapper that used max(unlock) as a proxy would silently disagree.
                "titleHistory": {
                    "lastTimePlayed": iso(END + timedelta(days=2, hours=3)),
                    "visible": True,
                    "canHide": True,
                },
                "detail": None,
                "friendsWhoPlayed": None,
                "alternateTitleIds": None,
                "contentBoards": None,
                "xboxLiveTier": "Full",
                "isStreamable": False,
            },
            {
                "titleId": "1824155023",
                "pfn": None,
                "bingId": "9c1e0000-0000-1000-8000-000000000002",
                "serviceConfigId": "b52c9a3d-6f10-4e2b-8c77-9d4e0a1b2c3d",
                "windowsPhoneProductId": None,
                "name": "Sundered Vault",
                "type": "Game",
                "devices": ["PC"],
                "displayImage": "https://store-images.s-microsoft.com/image/SYNTHETIC.fixture.boxart.vault",
                "mediaItemType": "Application",
                "modernTitleId": "1824155023",
                "isBundle": False,
                "achievement": {
                    "currentAchievements": 6,
                    "totalAchievements": 42,
                    "currentGamerscore": 125,
                    "totalGamerscore": 1000,
                    "progressPercentage": 12.5,
                    "sourceVersion": 1,
                },
                "stats": {"sourceVersion": 0},
                "gamePass": None,
                "images": None,
                "titleHistory": {
                    "lastTimePlayed": iso(END - timedelta(days=1, hours=6)),
                    "visible": True,
                    "canHide": True,
                },
                "detail": None,
                "friendsWhoPlayed": None,
                "alternateTitleIds": None,
                "contentBoards": None,
                "xboxLiveTier": "Full",
                "isStreamable": False,
            },
        ],
    }


def build_profile(titlehub):
    total = sum(t["achievement"]["currentGamerscore"] for t in titlehub["titles"])
    return {
        "_note": NOTE
        + " The gamertag below begins with U+0406 CYRILLIC CAPITAL LETTER BYELORUSSIAN-"
        "UKRAINIAN I, not a Latin I. That is on purpose: it is the homoglyph case "
        "Eet.Trackers.Core.Identity exists for, and having it in the default fixture "
        "means the zero-credential path exercises it every run.",
        "profileUsers": [
            {
                "id": XUID,
                "hostId": XUID,
                "settings": [
                    {"id": "Gamertag", "value": GAMERTAG},
                    {
                        "id": "GameDisplayPicRaw",
                        "value": "https://images-eds-ssl.xboxlive.com/image?url=SYNTHETIC.fixture.gamerpic&format=png",
                    },
                    {"id": "Gamerscore", "value": str(total)},
                ],
                "isSponsoredUser": False,
            }
        ],
    }


def write(path, doc):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(doc, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print("wrote", path)


def main():
    import os

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)))
    halo, unlock_by_index, catalogue = build_halo_achievements()
    titlehub = build_titlehub(halo)

    write(os.path.join(out, "achievements-halo-infinite.json"), halo)
    write(os.path.join(out, "achievements-recent.json"), build_recent(halo, unlock_by_index, catalogue))
    write(os.path.join(out, "titlehub-titlehistory.json"), titlehub)
    write(os.path.join(out, "profile-settings.json"), build_profile(titlehub))

    unlocked = [e for e in halo["achievements"] if e["progressState"] == "Achieved"]
    days = sorted({e["progression"]["timeUnlocked"][:10] for e in unlocked})
    print(
        "halo: %d achievements, %d unlocked, %d distinct unlock days, %s..%s"
        % (len(halo["achievements"]), len(unlocked), len(days), days[0], days[-1])
    )


if __name__ == "__main__":
    main()
